using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable CA1062 // Migration methods are generated and accept non-null migrationBuilder from runtime

// <auto-generated />
// This file is generated by Entity Framework migrations. Analyzer warnings for generated code are suppressed.

#nullable disable

namespace KunstButikken.ArtService.Migrations
{
    /// <inheritdoc />
    public partial class RemoveOldTitleDescription : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Description",
                table: "Arts");

            migrationBuilder.DropColumn(
                name: "Title",
                table: "Arts");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Arts",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Title",
                table: "Arts",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}

#pragma warning restore CA1062
