// Auto-generated by scripts/generate-env.mjs on 2025-11-30T22:05:48.969Z.
export const environment = {
  "production": false,
  "appName": "KunstButikken",
  "frontend": {
    "origin": "http://localhost:4200",
    "selfUrl": "http://localhost:4200"
  },
  "stripe": {
    "publishableKey": "\npk_test_51SIF0Y3vB30PF4SVy4rmu9F1Nc5ZRgagWDwCy4MYTDmha1cuWGqZi6h8f6Ox3unwQ12mtTUSVAonVR8HAPfdw5GR003qbhHP9Z"
  },
  "apis": {
    "gateway": "http://localhost:5100"
  },
  "keycloak": {
    "baseUrl": "http://localhost:8080",
    "realm": "kunstbutikken",
    "issuer": "http://localhost:8080/realms/kunstbutikken",
    "clientId": "kunstbutikken-frontend-ang",
    "clientSecret": ""
  }
} as const;
