// Auto-generated by scripts/generate-env.mjs on 2025-11-28T19:46:35.739Z.
export const environment = {
  "production": false,
  "appName": "KunstButikken",
  "frontend": {
    "origin": "http://localhost:4200",
    "selfUrl": "http://localhost:4200"
  },
  "stripe": {
    "publishableKey": ""
  },
  "apis": {
    "gateway": "http://localhost:5000"
  },
  "keycloak": {
    "baseUrl": "http://localhost:8080",
    "realm": "kunstbutikken",
    "issuer": "http://localhost:8080/realms/kunstbutikken",
    "clientId": "kunstbutikken-frontend-ang",
    "clientSecret": ""
  }
} as const;
