<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.OpenApi"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="Aspire.Hosting.Yarp"/>
        <PackageReference Include="Aspire.Keycloak.Authentication"/>
        <PackageReference Include="Scalar.Aspire"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="Application/KunstButikken.AuthGateway.Application.csproj"/>
        <ProjectReference Include="Domain/KunstButikken.AuthGateway.Domain.csproj"/>
        <ProjectReference Include="$(RepoRoot)KunstButikken.ServiceDefaults/KunstButikken.ServiceDefaults.csproj"/>
        <ProjectReference Include="$(RepoRoot)KunstButikken.IntegrationEvents.Contracts/KunstButikken.IntegrationEvents.Contracts.csproj"/>
        <ProjectReference Include="$(RepoRoot)KunstButikken.Common.Logging/KunstButikken.Common.Logging.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Application\**\*.cs"/>
        <Compile Remove="Domain\**\*.cs"/>
    </ItemGroup>
</Project>
