#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const thisDir = dirname(fileURLToPath(import.meta.url));
const envDir = join(thisDir, '..', 'src', 'environments');

const coalesce = (...values) => {
  for (const value of values) {
    if (typeof value === 'string' && value.length > 0) {
      return value;
    }
  }
  return '';
};

const envFromPrefix = Object.entries(process.env)
  .filter(([key]) => key.startsWith('NG_APP_'))
  .reduce((acc, [key, value]) => {
    const cleanKey = key.substring('NG_APP_'.length);
    acc[cleanKey] = value ?? '';
    return acc;
  }, /** @type {Record<string, string>} */ ({}));

const get = (key, fallback = '') => coalesce(envFromPrefix[key], process.env[key], fallback);

const production = process.env.NODE_ENV === 'production';

const environmentObject = {
  production,
  appName: 'KunstButikken',
  frontend: {
    origin: get('FRONTEND_ORIGIN', 'http://localhost:4200'),
    selfUrl: get('SELF_URL', get('FRONTEND_ORIGIN', 'http://localhost:4200'))
  },
  stripe: {
    publishableKey: get('STRIPE_PUBLISHABLE_KEY')
  },
  apis: {
    gateway: get('API_GATEWAY', 'http://localhost:5000')
  },
  keycloak: {
    baseUrl: get('KEYCLOAK_BASE_URL', 'http://localhost:8080'),
    realm: get('KEYCLOAK_REALM', 'KunstButikken'),
    issuer: get('KEYCLOAK_ISSUER', 'http://localhost:8080/realms/KunstButikken'),
    clientId: get('KEYCLOAK_CLIENT_ID', 'kunstbutikken-frontend-ang'),
    clientSecret: get('KEYCLOAK_CLIENT_SECRET', '')
  }
};

const banner = `// Auto-generated by scripts/generate-env.mjs on ${new Date().toISOString()}.\n`;
const serialized = `${banner}export const environment = ${JSON.stringify(environmentObject, null, 2)} as const;\n`;

await mkdir(envDir, { recursive: true });
const target = join(envDir, 'environment.ts');
let current = '';
try {
  current = await readFile(target, 'utf8');
} catch {
  current = '';
}

if (current.trim() === serialized.trim()) {
  console.log('[env] environment.ts already up to date');
} else {
  await writeFile(target, serialized, 'utf8');
  console.log('[env] Wrote environment.ts');
}

const prodTarget = join(envDir, 'environment.prod.ts');
const prodContent = 'import { environment as base } from \'./environment\';\n\nexport const environment = {\n  ...base,\n  production: true\n} as const;\n';

try {
  const existingProd = await readFile(prodTarget, 'utf8');
  if (existingProd.trim() !== prodContent.trim()) {
    await writeFile(prodTarget, prodContent, 'utf8');
    console.log('[env] Updated environment.prod.ts');
  }
} catch {
  await writeFile(prodTarget, prodContent, 'utf8');
  console.log('[env] Created environment.prod.ts');
}
