<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../KunstButikken.ArtService/Application/KunstButikken.ArtService.Application.csproj" />
    <ProjectReference Include="../KunstButikken.ArtService/Domain/KunstButikken.ArtService.Domain.csproj" />
    <ProjectReference Include="../KunstButikken.ArtService/Infrastructure/KunstButikken.ArtService.Infrastructure.csproj" />
    <ProjectReference Include="../KunstButikken.Common.Logging/KunstButikken.Common.Logging.csproj" />
    <ProjectReference Include="../KunstButikken.ServiceDefaults/KunstButikken.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
