<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Scalar.Aspire" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="All" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Aspire.Keycloak.Authentication" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Aspire.RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Application/KunstButikken.AuctionService.Application.csproj" />
    <ProjectReference Include="Infrastructure/KunstButikken.AuctionService.Infrastructure.csproj" />
    <ProjectReference Include="$(RepoRoot)KunstButikken.IntegrationEvents.Contracts/KunstButikken.IntegrationEvents.Contracts.csproj" />
    <ProjectReference Include="$(RepoRoot)KunstButikken.Common.Logging/KunstButikken.Common.Logging.csproj" />
    <ProjectReference Include="$(RepoRoot)KunstButikken.ServiceDefaults/KunstButikken.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Application\**\*.cs" />
    <Compile Remove="Infrastructure\**\*.cs" />
    <Compile Remove="Domain\**\*.cs" />
  </ItemGroup>

</Project>
