// <auto-generated />
// This file was moved into Infrastructure so migrations live in the Infrastructure project.

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using KunstButikken.AuctionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace KunstButikken.AuctionService.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("202511150002_SellerDisplayNameDefault")]
    public partial class SellerDisplayNameDefault : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "SellerDisplayName",
                table: "Auctions",
                type: "text",
                nullable: false,
                defaultValue: string.Empty,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "SellerDisplayName",
                table: "Auctions",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");
        }
    }
}

