// <auto-generated />
// This file was moved into Infrastructure so migrations live in the Infrastructure project.

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using KunstButikken.AuctionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace KunstButikken.AuctionService.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("202511150001_AddReservePrice")]
    public partial class AddReservePrice : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "ReservePrice",
                table: "Auctions",
                type: "numeric",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ReservePrice",
                table: "Auctions");
        }
    }
}

