// <auto-generated />
// This file is the model snapshot moved into Infrastructure.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using KunstButikken.AuctionService.Infrastructure.Persistence;

#nullable disable

namespace KunstButikken.AuctionService.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KunstButikken.AuctionService.Domain.Models.Auction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ArtId").HasColumnType("uuid");

                b.Property<DateTimeOffset>("EndsAt").HasColumnType("timestamp with time zone");

                b.Property<Guid>("SellerId").HasColumnType("uuid");

                b.Property<string>("SellerDisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue(string.Empty);

                b.Property<DateTimeOffset>("StartsAt").HasColumnType("timestamp with time zone");

                b.Property<decimal>("StartingPrice").HasColumnType("numeric");

                b.Property<decimal?>("WinningBid").HasColumnType("numeric");

                b.Property<Guid?>("WinnerId").HasColumnType("uuid");

                b.Property<int>("Status").HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Auctions");
            });

            modelBuilder.Entity("KunstButikken.AuctionService.Domain.Models.Bid", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AuctionId").HasColumnType("uuid");

                b.Property<Guid>("BidderId").HasColumnType("uuid");

                b.Property<decimal>("Amount").HasColumnType("numeric");

                b.Property<DateTimeOffset>("PlacedAt").HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("AuctionId");

                b.ToTable("Bids");
            });

            modelBuilder.Entity("KunstButikken.AuctionService.Domain.Models.Bid", b =>
            {
                b.HasOne("KunstButikken.AuctionService.Domain.Models.Auction")
                    .WithMany()
                    .HasForeignKey("AuctionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Bids");
            });
        }
    }
}

