<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="aspire.keycloak.authentication" />
    <PackageReference Include="aspire.rabbitmq.client" />
    <PackageReference Include="dotnetenv" />
    <PackageReference Include="microsoft.entityframeworkcore.relational" />
    <PackageReference Include="microsoft.extensions.servicediscovery" />
    <PackageReference Include="opentelemetry.exporter.opentelemetryprotocol" />
    <PackageReference Include="opentelemetry.extensions.hosting" />
    <PackageReference Include="opentelemetry.instrumentation.aspnetcore" />
    <PackageReference Include="opentelemetry.instrumentation.http" />
    <PackageReference Include="opentelemetry.instrumentation.runtime" />
    <PackageReference Include="rabbitmq.client" />
    <PackageReference Include="stripe.net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\KunstButikken.PaymentService.Domain.csproj" />
    <ProjectReference Include="..\Application\KunstButikken.PaymentService.Application.csproj" />
  </ItemGroup>
</Project>