<Project Sdk="Aspire.AppHost.Sdk/13.0.1">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>31935926-3bc6-42ee-8981-3d516bdef037</UserSecretsId>

    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
        <PackageReference Include="Aspire.Hosting.RabbitMQ" />
        <PackageReference Include="Aspire.Hosting.Keycloak" />
        <PackageReference Include="Aspire.Hosting.NodeJS" />
        <PackageReference Include="ModelContextProtocol.AspNetCore" />
        <PackageReference Include="ModelContextProtocol.Core" />
        <PackageReference Include="Scalar.Aspire" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(RepoRoot)KunstButikken.ServiceDefaults/KunstButikken.ServiceDefaults.csproj">
            <IsAspireProjectResource>false</IsAspireProjectResource>
        </ProjectReference>
    </ItemGroup>

</Project>
